README.md
example/playstore_scrapper_example.py
obsei/source/playstore_scrapper.py
requirements.in
requirements.txt

Google play store scrapper

---

obsei/source/playstore_scrapper.py

To fix https://github.com/lalitpagaria/obsei/issues/34

Scrapped payload do not have date field

---

example/daily_get_example.py
example/elasticsearch_example.py
example/jira_example.py
example/playstore_scrapper_example.py

To close https://github.com/lalitpagaria/obsei/issues/36

Fix examples as they are not working

---

README.md

Adding good example in README.md

---

.github/workflows/build.yml
obsei/analyzer/pii_analyzer.py
requirements.txt
test/conftest.py

Adding CI testing on multiple OS and python version

---

obsei/misc/utils.py
obsei/sink/http_sink.py

[Http Sink] To fix datetime conversion to string

---

obsei/sink/slack_sink.py

[Slack] Convert string to unicode

---

sample-ui/ui.py

Fixed https://github.com/lalitpagaria/obsei/issues/99

favicon fix

---

obsei/sink/http_sink.py
sample-ui/ui.py

To fix https://github.com/lalitpagaria/obsei/issues/100

Use urllib instead of requests to mitigate SSL issue in windows systems

---

README.md
example/google_news_example.py
obsei/analyzer/classification_analyzer.py
obsei/analyzer/ner_analyzer.py
obsei/analyzer/translation_analyzer.py

This is hack solution till we have proper solution.
To fix #113

Trimming excessive text before passing to model

---

obsei/source/appstore_scrapper.py
obsei/source/reddit_scrapper.py

fixing error regarding offset-naive and offset-aware datetimes comparison

---

.github/workflows/build.yml
obsei/analyzer/base_analyzer.py
obsei/analyzer/classification_analyzer.py
obsei/analyzer/dummy_analyzer.py
obsei/analyzer/ner_analyzer.py
obsei/analyzer/pii_analyzer.py
obsei/analyzer/sentiment_analyzer.py
obsei/analyzer/translation_analyzer.py
obsei/configuration.py
obsei/preprocessor/text_cleaner.py
obsei/preprocessor/text_cleaning_function.py
obsei/processor.py
obsei/sink/base_sink.py
obsei/sink/dailyget_sink.py
obsei/sink/elasticsearch_sink.py
obsei/sink/http_sink.py
obsei/sink/logger_sink.py
obsei/sink/pandas_sink.py
obsei/sink/zendesk_sink.py
obsei/source/appstore_scrapper.py
obsei/source/email_source.py
obsei/source/google_news_source.py
obsei/source/playstore_reviews.py
obsei/source/playstore_scrapper.py
obsei/source/reddit_scrapper.py
obsei/source/reddit_source.py
obsei/source/twitter_source.py
obsei/workflow/store.py
obsei/workflow/workflow.py
test/test_text_cleaner.py

to fix https://github.com/lalitpagaria/obsei/issues/122 and https://github.com/lalitpagaria/obsei/issues/121

mypy fixes along with adding to CI

---

example/app_store_scrapper_example.py
example/playstore_scrapper_example.py
obsei/analyzer/classification_analyzer.py
obsei/analyzer/dummy_analyzer.py
obsei/analyzer/pii_analyzer.py
obsei/analyzer/sentiment_analyzer.py
obsei/misc/web_search.py
obsei/preprocessor/text_cleaner.py
obsei/sink/dailyget_sink.py
obsei/sink/elasticsearch_sink.py
obsei/sink/http_sink.py
obsei/sink/jira_sink.py
obsei/sink/logger_sink.py
obsei/sink/pandas_sink.py
obsei/sink/slack_sink.py
obsei/sink/zendesk_sink.py
obsei/source/appstore_scrapper.py
obsei/source/email_source.py
obsei/source/google_news_source.py
obsei/source/playstore_reviews.py
obsei/source/playstore_scrapper.py
obsei/source/reddit_scrapper.py
obsei/source/reddit_source.py
obsei/source/twitter_source.py
obsei/source/website_crawler_source.py
sample-ui/config.yaml

To fix #129
Also adding ignore overides for https://github.com/lalitpagaria/obsei/issues/127

adding app name support for app and play store

---

obsei/preprocessor/text_cleaner.py
obsei/source/google_news_source.py

To fix https://github.com/lalitpagaria/obsei/issues/142 and https://github.com/lalitpagaria/obsei/issues/141

Ignoring error during cleaning and fixing exception in google news module

---

obsei/source/email_source.py

One mail was repeated in each iteration previously which has been removed now.

Email source fixed, no duplicates in each iteration

---

tutorials/Example3_AppStore_PreProcessing_Classification_Pandas.ipynb
tutorials/Example3_PlayStore_PreProcessing_Classification_Pandas.ipynb

Added Colab Tutorials in Obsei.

Colab Tutorials Added

---

.github/workflows/build.yml
obsei/analyzer/ner_analyzer.py
test/conftest.py
test/test_analyzer.py

have a look when its convinient. 
Implemented `SpacyNerAnalyzer` and renamed  `NerAnalyzer` to `TransformerNerAnalyzer` . Also updated the tests ,|

spacy ner analyzer , #165 enhancement

---

obsei/source/google_news_source.py

Handle Null case when crawler failed to fetch article

---

obsei/source/google_news_source.py

To fix https://github.com/obsei/obsei/issues/174

Creating quoted query before passing to GNews client

---

example/app_store_scrapper_example.py
example/playstore_scrapper_example.py
obsei/source/appstore_scrapper.py
obsei/source/playstore_scrapper.py

To complete https://github.com/obsei/obsei/issues/178

Adding app_url support to appstore and playstore scrappers

---

example/with_sdk_config_file.py
obsei/analyzer/base_analyzer.py
obsei/configuration.py
obsei/postprocessor/base_postprocessor.py
obsei/preprocessor/base_preprocessor.py
obsei/sink/base_sink.py
obsei/sink/elasticsearch_sink.py
obsei/sink/jira_sink.py
obsei/sink/slack_sink.py
obsei/sink/zendesk_sink.py
obsei/source/base_source.py
obsei/source/email_source.py
obsei/source/facebook_source.py
obsei/source/playstore_reviews.py
obsei/source/reddit_source.py
obsei/source/twitter_source.py

Fixing https://github.com/obsei/obsei/issues/188

Bug fix: Use of BaseSettings Causing regression so reverting the changes

---

README.md
example/jira_example.py
obsei/source/email_source.py
obsei/source/playstore_reviews.py
obsei/source/reddit_scrapper.py
obsei/source/twitter_source.py
sample-ui/config.yaml

Fixing https://github.com/obsei/obsei/issues/188

Bug fix: Fix Twitter Source Config import issue

---

obsei/analyzer/classification_analyzer.py
test/conftest.py
test/test_analyzer.py

The initial draft for text classifier which will resolve #77

add text classification analyzer

---

README.md
obsei/__init__.py
obsei/analyzer/__init__.py
obsei/analyzer/base_analyzer.py
obsei/configuration.py
obsei/postprocessor/__init__.py
obsei/postprocessor/base_postprocessor.py
obsei/preprocessor/__init__.py
obsei/preprocessor/base_preprocessor.py
obsei/sink/__init__.py
obsei/sink/base_sink.py
obsei/sink/elasticsearch_sink.py
obsei/sink/jira_sink.py
obsei/sink/slack_sink.py
obsei/sink/zendesk_sink.py
obsei/source/__init__.py
obsei/source/base_source.py
obsei/source/email_source.py
obsei/source/facebook_source.py
obsei/source/playstore_reviews.py
obsei/source/reddit_source.py
obsei/source/twitter_source.py
obsei/workflow/base_store.py
test/test_imports.py

To fix https://github.com/obsei/obsei/issues/192

Bug: Fixing import issues along

---

README.md
example/twitter_source_example.py
obsei/source/twitter_source.py

Twitter recently changed the output format so reverting it to older message format using their output_format option
Fixes https://github.com/obsei/obsei/issues/197

Reverting to older messaging format for Twitter v2 API

---

.github/workflows/build.yml
requirements.in
requirements.txt

Fixes https://github.com/obsei/obsei/issues/95

Enabling CI caching

---

.github/workflows/build.yml
requirements.txt

To fix https://github.com/obsei/obsei/issues/216

Fixing typing-extensions dependency issue on python 3.7

---

.github/workflows/build.yml
ATTRIBUTION.md
LICENSE
README.md
obsei/sink/zendesk_sink.py
obsei/source/twitter_source.py
obsei/source/website_crawler_source.py
requirements.in
requirements.txt
sample-ui/requirements.txt

Fixes https://github.com/obsei/obsei/issues/220

Removing third party dependencies with strong copyleft licenses

---

README.md
example/youtube_scrapper_example.py
obsei/analyzer/ner_analyzer.py
obsei/misc/utils.py
obsei/misc/youtube_reviews_scrapper.py
obsei/preprocessor/text_cleaning_function.py
obsei/source/__init__.py
obsei/source/appstore_scrapper.py
obsei/source/reddit_scrapper.py
obsei/source/youtube_scrapper.py
sample-ui/config.yaml

Fixes https://github.com/obsei/obsei/issues/223

Youtube integration via scrapper

---

README.md
example/google_news_example.py
obsei/source/google_news_source.py
obsei/source/twitter_source.py

Hello, I have created this new PR to see if we can finally make it🥲

Fix TwitterSource username bug, add Gnews proxy
